### ISSUE TITLE
Glossary items don't include page contents

### ISSUE THREAD

**Issue by nuke-web3** [celestiaorg/celestia.org#51]
In https://celestia.org/glossary/modular-stack  and other glossary entries I would not expect it to only the YAML `description` in [src/content/glossary/modular-stack.md](https://github.com/celestiaorg/celestia.org-new/blob/main/src/content/glossary/modular-stack.md), rather I would like the whole of the page content to be rendered.

![Image](https://github.com/user-attachments/assets/eb56a8d7-c59e-4081-82d6-6a902982ad99)

cc @alex-beckett , as @jcstein suggested we should ask you about this 🙏

**Comment by jcstein** [comment]
also, the "9-18" seems like it shouldn't be rendered and looks like it just an index of each letter in the glossary (18 total)

**Comment by alex-beckett** [comment]
thanks, fixed with https://github.com/celestiaorg/celestia.org-new/pull/53

**Comment by jcstein** [comment]
this is not resolved from #53 and 53 seems to be a regression (see #54 )

<img width="1920" alt="Image" src="https://github.com/user-attachments/assets/fff3f593-efa3-428d-8cff-eeafb52e7787" />

**Comment by alex-beckett** [comment]
this should be fixed now with https://github.com/celestiaorg/celestia.org-new/pull/55

**Comment by nuke-web3** [comment]
seems to wok well now! Thanks!
